-- Snowflake warehouse setup. Run once after creating the database.
CREATE DATABASE IF NOT EXISTS OLIST_DWH;
CREATE SCHEMA IF NOT EXISTS OLIST_DWH.RAW;
CREATE SCHEMA IF NOT EXISTS OLIST_DWH.ANALYTICS;

CREATE OR REPLACE TABLE OLIST_DWH.RAW.CUSTOMERS (
  CUSTOMER_ID STRING, CUSTOMER_UNIQUE_ID STRING, CUSTOMER_ZIP_CODE_PREFIX INTEGER,
  CUSTOMER_CITY STRING, CUSTOMER_STATE STRING
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.ORDERS (
  ORDER_ID STRING, CUSTOMER_ID STRING, ORDER_STATUS STRING,
  ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ, ORDER_APPROVED_AT TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ, ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.ORDER_ITEMS (
  ORDER_ID STRING, ORDER_ITEM_ID INTEGER, PRODUCT_ID STRING, SELLER_ID STRING,
  SHIPPING_LIMIT_DATE TIMESTAMP_NTZ, PRICE NUMBER(12,2), FREIGHT_VALUE NUMBER(12,2)
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.ORDER_PAYMENTS (
  ORDER_ID STRING, PAYMENT_SEQUENTIAL INTEGER, PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS INTEGER, PAYMENT_VALUE NUMBER(12,2)
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.ORDER_REVIEWS (
  REVIEW_ID STRING, ORDER_ID STRING, REVIEW_SCORE INTEGER,
  REVIEW_COMMENT_TITLE STRING, REVIEW_COMMENT_MESSAGE STRING
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.PRODUCTS (
  PRODUCT_ID STRING, PRODUCT_CATEGORY_NAME STRING, PRODUCT_NAME_LENGHT INTEGER,
  PRODUCT_DESCRIPTION_LENGHT INTEGER, PRODUCT_PHOTOS_QTY INTEGER,
  PRODUCT_WEIGHT_G INTEGER, PRODUCT_LENGTH_CM INTEGER, PRODUCT_HEIGHT_CM INTEGER, PRODUCT_WIDTH_CM INTEGER
);
CREATE OR REPLACE TABLE OLIST_DWH.RAW.SELLERS (
  SELLER_ID STRING, SELLER_ZIP_CODE_PREFIX INTEGER, SELLER_CITY STRING, SELLER_STATE STRING
);

CREATE OR REPLACE TABLE OLIST_DWH.ANALYTICS.CUSTOMER_360 (
  CUSTOMER_ID STRING, CUSTOMER_UNIQUE_ID STRING, CUSTOMER_CITY STRING, CUSTOMER_STATE STRING,
  ORDER_COUNT INTEGER, COMPLETED_ORDER_COUNT INTEGER, TOTAL_REVENUE NUMBER(14,2),
  TOTAL_FREIGHT NUMBER(14,2), AVERAGE_ORDER_VALUE NUMBER(14,2),
  FIRST_ORDER_DATE TIMESTAMP_NTZ, LAST_ORDER_DATE TIMESTAMP_NTZ,
  AVG_DELIVERY_DAYS NUMBER(10,2), AVG_REVIEW_SCORE NUMBER(5,2),
  PRIMARY_PAYMENT_TYPE STRING
);
