version: 2

sources:
  - name: raw
    schema: RAW
    database: OLIST_DWH
    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: ORDER_ITEMS
      - name: ORDER_PAYMENTS
      - name: ORDER_REVIEWS
      - name: PRODUCTS
      - name: SELLERS

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
  - name: fct_customer_360
    columns:
      - name: customer_id
        tests: [not_null]
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [not_null, unique]
